name: Coverage and Sanitizers

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    shell: bash

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  analyse:
    name: Coverage and Sanitizers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Conan
        run: |
          pip3 install wheel setuptools
          pip3 install conan --upgrade

      - name: Configure CMake
        working-directory: ${{github.workspace}}
        run: cmake -B build -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D BUILD_TESTS:BOOL=TRUE -D ENABLE_COVERAGE:BOOL=TRUE -D ENABLE_SANITIZERS:BOOL=TRUE
        env:
          CC: gcc
          CXX: g++

      - name: Build
        working-directory: ${{github.workspace}}
        run: cmake --build build --config ${{env.BUILD_TYPE}}

      - name: Test, get coverage reports and run sanitizers
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Upload coverage reports to CodeCov
        working-directory: ${{github.workspace}}/build
        run: bash <(curl -s https://codecov.io/bash)
